# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# the build will trigger on any changes to the master branch
trigger:
- master

# the build will run on a Microsoft hosted agent, using the lastest Windows VM Image
pool:
  vmImage: 'ubuntu-latest'

# these variables are available throughout the build file
# just the build configuration is defined, in this case we are building Release packages
variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build '
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --interactive'
    projects: 'SONY.PTP700.SPP/SONY.PTP700.SPP.csproj'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'SONY.PTP700.SPP/SONY.PTP700.SPP.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '3d77afcb-a6e8-4ae6-87cb-78ceee997060'
    versioningScheme: 'off'
    allowPackageConflicts: true